name: Build R for Ubuntu-22.04

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: jammy
      UBUNTU_CODENAME: jammy
      R_HOME: /usr/local/lib/R

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: apt
        run: apt-get update && apt-get install -y wget
      -
        name: ppa
        run: wget https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/scripts/install_R_ppa.sh | sudo bash
      -
        name: install
        run: wget https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/scripts/install_R_source.sh | sudo bash
      -
        name: setup
        run: wget https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/scripts/setup_R.sh | sudo bash
      -
        name: test
        run: |
          Rscript -e "stats::rnorm(5)"
          Rscript -e "sessionInfo()"
