name: Build R for Ubuntu-22.04

on:
  schedule:
    - cron:  '0 2 ? * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      UBUNTU_VERSION: jammy

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: R ppa
        run: wget https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/scripts/install_R_ppa.sh | sudo bash
      -
        name: R install
        run: wget https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/scripts/install_R_source.sh | sudo bash
