name: Build R for Ubuntu-22.04 (Runner)

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: jammy

    steps:
      -
        name: Remove default R installation
        run: sudo apt-get remove -y r-base-core r-base
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Build
        run: sudo bash tools/build.sh
